---
title: "CRC_KRAS_Age"
author: "Shruti Kakan"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("TCGAbiolinks")
library("limma")
library("edgeR")
library("glmnet")
library("factoextra")
library("FactoMineR")
library("caret")
library("SummarizedExperiment")
library("gplots")
library("survival")
library("survminer")
library("RColorBrewer")
library("gProfileR")
library("genefilter")

setwd("~/Documents/TCGA/TCGA/")
```

## R Markdown

```{r}
#TCGA Data
library(TCGAbiolinks)
GDCprojects = getGDCprojects()
head(GDCprojects[c("project_id", "name")])
TCGAbiolinks:::getProjectSummary("TCGA-COAD")

#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("TCGAbiolinks")


```

#Obtain Colon Adenocarconoma datasets COAD
#Querying all RNA-seq data from COAD project
#READ is rectal adenocarcinoma
```{r}
query_COAD = GDCquery(
  project = "TCGA-COAD",
  data.category = "Transcriptome Profiling",
  experimental.strategy = "RNA-Seq",
  workflow.type = "STAR - Counts")
query_READ = GDCquery(
  project =  "TCGA-READ",
  data.category = "Transcriptome Profiling",
  experimental.strategy = "RNA-Seq",
  workflow.type = "STAR - Counts")

View(getResults(query_COAD))
View(getResults(query_READ))
```


```{r}
coad_res = getResults(query_COAD) # make results as table
# head(lihc_res) # data of the first 6 patients.
colnames(coad_res) # columns present in the table
head(coad_res$sample_type) # first 6 types of tissue.
summary(factor(coad_res$sample_type)) # summary of distinct tissues types present in this study

read_res = getResults(query_READ) # make results as table
# head(lihc_res) # data of the first 6 patients.
colnames(read_res) # columns present in the table
head(read_res$sample_type) # first 6 types of tissue.
summary(factor(read_res$sample_type)) # summary of distinct tissues types present in this study

```

There are 82 normal tissue samples

Downloading the data file
```{r}
GDCdownload(query = query_TCGA)
```


```{r}

```

